version: '3' 
  
services: 
   api: 
     image: rexbhaws/backend:latest         
     ports: 
       - "8000:8000" 
  
   web: 
     image: rexbhaws/frontend:latest 
     ports: 
       - "3000:3000"
